Solve #3 Recuperação de Senha
HackathonOrc/hackathonTime1 pull request #13
Opened 2021-07-07 23:24 UTC by MauricioMachadoFF

## Neste pull request se realizou:

- US 03

## Checklist

- [ x] Indicar pelo menos um membro da gerência a ser responsável por analisar as modificações submetidas (Reviewers).
- [ x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [ x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:

- Solve #X IssueName (Caso Padrão)
- WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-07-08 20:23 UTC, MatheusBlanco requested changes
Perfeito galera! Arrasaram demais e rápido demais!

Dêem só uma olhada nos comentários que deixei, e queria pedir duas alterações visuais também:

![image](https://user-images.githubusercontent.com/37380789/124985667-0baec100-e011-11eb-92b3-96ec7e3501cd.png)
Esse texto acima do e-mail está mt grande e mt colado no e-mail. Reduzam o tamanho dele ou aumentem a fonte do input, na página de inserir e-mail

![image](https://user-images.githubusercontent.com/37380789/124985767-30a33400-e011-11eb-9a7f-87a365eee1f6.png)
Tentem separar esse botão do rodapé dessa caixa branca tbm, na página de digitar nova senha

2021-07-08 20:23 UTC, MatheusBlanco commented on app/src/services/users.ts
> +        //console.error(`Falha na requisição: ${error}`);
podem tirar esse comment daqui

2021-07-08 20:23 UTC, MatheusBlanco commented on server/src/controllers/passwordController.ts
> +                    <h1>Prezado nome,</h1>
esse nome está fixo, tentem mudar ele para receber o nome do usuário

2021-07-09 04:32 UTC, MauricioMachadoFF commented on server/src/controllers/passwordController.ts
> +                    <h1>Prezado nome,</h1>
Consegui fazer para o nome ser alterado com base no name do usuário que pediu para recuperar a senha

2021-07-09 04:46 UTC, MauricioMachadoFF commented
Alterações realizadas

2021-07-09 13:13 UTC, MatheusBlanco approved these changes
Perfeito!

2021-07-09 13:14 UTC, merged